/** Community Wayfinding: model rationale is shown as an auditable route record, never as a hidden score or diagnosis. */
import { getDecisionForRecord, type ScreeningRecord } from "@/data/mockData";
import { BrainCircuit, CircleAlert, Compass, Info, Sparkles } from "lucide-react";
import { Link } from "wouter";

export function DecisionSupportPanel({ record, compact = false }: { record: ScreeningRecord; compact?: boolean }) {
  const decision = getDecisionForRecord(record); const shown = compact ? decision.factors.slice(0, 3) : decision.factors;
  return <section className={`decision-panel ${compact ? "decision-panel--compact" : ""}`} aria-label="PxK Route Engine explanation"><div className="decision-panel-head"><div><p className="eyebrow">Transparent decision support</p><h3><BrainCircuit className="h-5 w-5" />{decision.engine}</h3></div><span className={`decision-status ${decision.status === "Priority clinical review" ? "decision-status--priority" : ""}`}>{decision.status === "Priority clinical review" ? <CircleAlert /> : <Compass />}{decision.status}</span></div><div className="decision-route"><span>Potential route</span><strong>{decision.potentialSpecialty}</strong><p>{decision.summary}</p></div><div className="factor-trace"><div className="factor-trace-head"><p className="eyebrow">Answer trace</p><span>{shown.length} factors used</span></div>{shown.map((item, index) => <div className={`factor-row factor-row--${item.role}`} key={`${item.label}-${index}`}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{item.label}</strong><p>{item.answer}</p></div><em>{item.role === "priority" ? "Priority cue" : item.role === "route" ? "Routing context" : "Supporting context"}</em></div>)}</div>{!compact && <div className="model-boundary"><Info /><p><strong>What this means:</strong> {decision.nextStep}</p></div>}<div className="decision-foot"><span><Sparkles />No diagnosis or treatment recommendation</span>{!compact && <Link href="/model">Read model card</Link>}</div></section>;
}
