/** Community Wayfinding: the header pairs route-led pill navigation with a persistent language choice and a direct screening entry. */
import { LanguageSelector } from "@/components/LanguageSelector";
import { PillNav } from "@/components/PillNav";
import type { Language } from "@/data/mockData";
import { SITE_TEXT } from "@/data/siteI18n";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
function scrollToId(id: string, navigate: (path: string) => void, location: string) { if (location !== "/") { navigate("/"); window.setTimeout(() => document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }), 80); return; } document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }
export function Header({ language, setLanguage }: { language: Language; setLanguage: (language: Language) => void }) { const [location, navigate] = useLocation(); const [scrolled, setScrolled] = useState(false); const text = SITE_TEXT[language]; useEffect(() => { const handler = () => setScrolled(window.scrollY > 16); handler(); window.addEventListener("scroll", handler, { passive: true }); return () => window.removeEventListener("scroll", handler); }, []); const nav = [{ href: "/", label: text.home }, { href: "/how-it-works", label: text.how }, { href: "/patient", label: text.health }, { href: "/analytics", label: text.analytics }, { href: "/doctor", label: text.provider }]; return <header className={`site-header site-header--pill ${scrolled ? "site-header--scrolled" : ""}`}><div className="container pill-nav-wrap"><PillNav items={nav} activeHref={location} /><div className="header-route-actions"><LanguageSelector value={language} onChange={setLanguage} className="language-select--pill" /><button className="btn btn-primary btn-small" onClick={() => scrollToId("demo", navigate, location)}>{text.start}</button></div></div></header>; }
