/** Community Wayfinding: the header pairs route-led pill navigation with a persistent language choice and a direct screening entry. */
import { LanguageSelector } from "@/components/LanguageSelector";
import { PillNav } from "@/components/PillNav";
import type { Language } from "@/data/mockData";
import { SITE_TEXT } from "@/data/siteI18n";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { LogIn, LogOut, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useLocation } from "wouter";
function scrollToId(id: string, navigate: (path: string) => void, location: string) { if (location !== "/") { navigate("/"); window.setTimeout(() => document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }), 80); return; } document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }
export function Header({ language, setLanguage }: { language: Language; setLanguage: (language: Language) => void }) { const [location, navigate] = useLocation(); const [scrolled, setScrolled] = useState(false); const { user, isAuthenticated, loading, logout } = useAuth(); const text = SITE_TEXT[language]; useEffect(() => { const handler = () => setScrolled(window.scrollY > 16); handler(); window.addEventListener("scroll", handler, { passive: true }); return () => window.removeEventListener("scroll", handler); }, []); const nav = [{ href: "/", label: text.home }, { href: "/how-it-works", label: text.how }, { href: "/patient", label: text.health }, { href: "/analytics", label: text.analytics }, { href: "/doctor", label: text.provider }]; const profileInitial = user?.name?.trim().charAt(0).toUpperCase() || "P"; return <header className={`site-header site-header--pill ${scrolled ? "site-header--scrolled" : ""}`}><div className="container pill-nav-wrap"><PillNav items={nav} activeHref={location} /><div className="header-route-actions"><LanguageSelector value={language} onChange={setLanguage} className="language-select--pill" />{!loading && (isAuthenticated ? <div className="account-actions"><Link className="profile-link" href="/history" title={text.history} aria-label={`${text.profile}: ${text.history}`}><span className="profile-avatar" aria-hidden="true">{profileInitial}</span><UserRound /><span className="profile-link-label">{text.history}</span></Link><button className="account-button" title={text.signOut} aria-label={text.signOut} onClick={() => void logout()}><LogOut /><span>{text.signOut}</span></button></div> : <button className="account-button account-button--signin" onClick={startLogin}><LogIn /><span>{text.signIn}</span></button>)}<button className="btn btn-primary btn-small" onClick={() => scrollToId("demo", navigate, location)}>{text.start}</button></div></div></header>; }
