/** Community Wayfinding: the header is a compact route-control with direct access to a patient’s ongoing workflow. */
import { BrandMark } from "@/components/BrandMark";
import { LanguageSelector } from "@/components/LanguageSelector";
import type { Language } from "@/data/mockData";
import { SITE_TEXT } from "@/data/siteI18n";
import { Menu, X } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useLocation } from "wouter";
function scrollToId(id: string, navigate: (path: string) => void, location: string) { if (location !== "/") { navigate("/"); window.setTimeout(() => document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }), 80); return; } document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }
export function Header({ language, setLanguage }: { language: Language; setLanguage: (language: Language) => void }) { const [location, navigate] = useLocation(); const [menuOpen, setMenuOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const text = SITE_TEXT[language]; useEffect(() => { const handler = () => setScrolled(window.scrollY > 16); handler(); window.addEventListener("scroll", handler, { passive: true }); return () => window.removeEventListener("scroll", handler); }, []); const closeMenu = () => setMenuOpen(false); const goTo = (id: string) => { scrollToId(id, navigate, location); closeMenu(); }; const nav = [{ href: "/", label: text.home }, { href: "/how-it-works", label: text.how }, { href: "/patient", label: text.health }, { href: "/analytics", label: text.analytics }]; return <header className={`site-header ${scrolled ? "site-header--scrolled" : ""}`}><div className="container flex items-center justify-between gap-4 py-3.5 lg:py-4"><Link href="/" aria-label="PxK home" onClick={closeMenu}><BrandMark /></Link><nav className="hidden items-center gap-6 xl:flex" aria-label="Primary navigation">{nav.map((item) => <Link key={item.href} className={`nav-link ${location === item.href ? "active" : ""}`} href={item.href}>{item.label}</Link>)}</nav><div className="hidden items-center gap-3 lg:flex"><LanguageSelector value={language} onChange={setLanguage} /><button className="btn btn-primary btn-small" onClick={() => goTo("demo")}>{text.start}</button></div><div className="flex items-center gap-2 lg:hidden"><LanguageSelector value={language} onChange={setLanguage} className="language-select--compact" /><button className="icon-button" onClick={() => setMenuOpen((open) => !open)} aria-label={menuOpen ? "Close navigation" : "Open navigation"} aria-expanded={menuOpen}>{menuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div></div>{menuOpen && <div className="mobile-menu lg:hidden">{nav.map((item) => <Link key={item.href} href={item.href} onClick={closeMenu}>{item.label}</Link>)}<Link href="/history" onClick={closeMenu}>{text.history}</Link><button className="btn btn-primary" onClick={() => goTo("demo")}>{text.start}</button></div>}</header>; }
